# Generated by Django 5.0 on 2023-12-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('magic', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('brokerTime', models.DateTimeField()),
                ('updateTime', models.DateTimeField()),
                ('openPrice', models.FloatField()),
                ('volume', models.FloatField()),
                ('swap', models.FloatField()),
                ('realizedSwap', models.FloatField()),
                ('unrealizedSwap', models.FloatField()),
                ('commission', models.FloatField()),
                ('realizedCommission', models.FloatField()),
                ('unrealizedCommission', models.FloatField()),
                ('realizedProfit', models.FloatField()),
                ('reason', models.CharField(max_length=100)),
                ('accountCurrencyExchangeRate', models.FloatField()),
                ('brokerComment', models.TextField()),
                ('currentPrice', models.FloatField()),
                ('currentTickValue', models.FloatField()),
                ('unrealizedProfit', models.FloatField()),
                ('profit', models.FloatField()),
                ('comment', models.TextField()),
                ('updateSequenceNumber', models.IntegerField()),
            ],
        ),
    ]
