from django.db import models

class Position(models.Model):
    id = models.CharField(max_length=100, primary_key=True)
    type = models.CharField(max_length=100)
    platform = models.CharField(max_length=100)
    symbol = models.CharField(max_length=100)
    magic = models.IntegerField()
    time = models.DateTimeField()
    brokerTime = models.DateTimeField()
    updateTime = models.DateTimeField()
    openPrice = models.FloatField()
    volume = models.FloatField()
    swap = models.FloatField()
    realizedSwap = models.FloatField()
    unrealizedSwap = models.FloatField()
    commission = models.FloatField()
    realizedCommission = models.FloatField()
    unrealizedCommission = models.FloatField()
    realizedProfit = models.FloatField()
    reason = models.CharField(max_length=100)
    accountCurrencyExchangeRate = models.FloatField()
    brokerComment = models.TextField()
    currentPrice = models.FloatField()
    currentTickValue = models.FloatField()
    unrealizedProfit = models.FloatField()
    profit = models.FloatField()
    comment = models.TextField()
    updateSequenceNumber = models.IntegerField()